### ISSUE TITLE
Possibility of running on Windows?

### ISSUE THREAD

**Issue by musicalman** [haoheliu/voicefixer#22]
Hello, I stumbled on this repo and found it really interesting. The demos in particular impressed me. I have some old/bad quality speech recordings I'd like to try and enhance, but I'm having trouble running any of the code.

I am running Windows 10 home, Python 3.9.12 at the moment. No GPU present right now, so that may be a problem? I understand that the code is not well tested on Windows yet. Nevertheless, I am completely ignorant when it comes to getting these sorts of things to run; without clear steps to follow, I am lost.

If there are legitimate issues running on Windows, I'd like to do my part in making them known, but I'm taking a shot in the dark here. I still hope I can be helpful though!

I assume that the intended workflow for testing is to read an audio file eg. wav, aiff, raw PCM data etc. and process it, creating a new output file? But please correct me if I'm wrong.

I followed instructions in readme.md to try and use the Streamlit app. Specifically, I ran these commands:
pip install voicefixer==0.0.17
git clone https://github.com/haoheliu/voicefixer.git
cd voicefixer
pip install streamlit
streamlit run test/streamlit.py
At this point a Windows firewall dialog comes up and I click allow.
Throughout this process, no errors seem to show up. But the models do not appear to download (no terminal updates, and I let it sit for about a day with no changes). Streamlit page remains blank. The last thing I see in terminal is:
"  You can now view your Streamlit app in your browser.
  Local URL: http://localhost:8501
  Network URL: http://10.0.0.37:8501"
That local URL is the one shown in the address bar.

So yeah I'm quite lost. What do you advise?
Thanks in advance!

**Comment by haoheliu** [comment]
@musicalman Thanks for pointing out the problem.  Sorry for the confusion. It's probability because the windows system does not have **wget** command by nature. So I would suggest trying to install the WGET command (the command I used to download the model) on windows and add the command to the system path. 

If you check the terminal when you run streamlit, I guess you can see something like "wget: command not found", which indicates you need to install wget first.

**Comment by haoheliu** [comment]
@musicalman Five MB is expected. Because the model is downloaded somewhere else. The model should be downloaded into the home directory (C:\\Users\\xxxxxx\\.cache/voicefixer/analysis_module/checkpoints/vf.ckpt). Please check if the model is properly downloaded. If the model is downloaded but still cannot run properly please let me know. I'll try to reproduce it on a windows machine.

Thanks.

**Comment by musicalman** [comment]
Aha, that file did not exist. However, I managed to get voicefixer running directly from Python without streamlit.

Just running voicefixer/test/test.py seems to work. For now I'm just changing paths in test.py to test different files.

Streamlit still isn't launching a web page. Not sure where to go with that.
