### ISSUE TITLE
Some problems and questions. 

### ISSUE THREAD

**Issue by Aspector1** [haoheliu/voicefixer#28]
Hello! 
I installed your neural network and ran it in Desktop App mode, but I don't see the "Turn on GPU" switch here. This is the first question.
Second question: How do I use the models from the demo page? GSR_UNet, VF_Unet, Oracle?

Thanks in advance for the answer!

**Comment by haoheliu** [comment]
Hi,

Thanks for the interest. When you run the desktop app for the first time, the webpage will leave blank for several minutes, during which the pretrained model is downloaded. May be after giving the app some more time, the "Turn on GPU" button will appear.

1. VF_Unet stands for the voicefixer model you use by default in this repo.

2. Oracle stands for the neural vocoder. You can also access it in this repo. Note that neural vocoder cannot perform restoration, it is mainly used to demonstrate the ability of neural vocoder. We open the API of neural vocoder in this repo. You can have a try if you are interested.

3. GSR_UNet is the baseline of our paper. Unfortunately we do not code GSR_UNet in this repo because its performance is not as good as VF_Unet. If you are interested you can train a GSR_UNet yourself using [this repo](https://github.com/haoheliu/voicefixer_main).

Thanks,
Haohe
